input_data:
    # Data location can be local directory path or sftp server path
    data_location: local
    data_format: csv
    # If sftp, use this authenticaton
    # SFTP authentication data
    sftp_directory: /mnt/pool0/RADAR-CNS/HDFS_CSV/output-gzip/RADAR-ART-KCL-s1/
    sftp_host: radar-base-nas.brc.iop.kcl.ac.uk
    sftp_username: hsankesa
    sftp_password:
    sftp_private_key: ~/.ssh/id_rsa
    # Else select local path
    local_directory: ../../../ART/data_cleaning/fitbit_data/

project:
    project_name: x
    pool_size: 8

features:
    # Here we can select existing feature in feature directory or give path of another feature class
    - 'heart-rate-sleep-features'

output_data:
    # Output location can be a pgdb, or a local
    output_location: local
    output_format: csv #can be xlsx, csv
    # If location in pg table then we would need postgres authentication
    postgres_username:
    postgres_password:
    postgres_host:
    postgres_port:
    postgres_database:
    postgres_tablename:
    # Else local directory
    output_directory: ../test_pipeline
